### PR TITLE
Hide input for posts on own profile page #3

### PR DESCRIPTION
**Pull request by gaurav-handysolver**
debug: initially, we are using variable to hold the element in script before removing the element. Now we are done this operation without using any variables.

#10

### CODE REVIEW

**Comment by donni106** [comment]
I found another problem! In Spaces the post section is also removed, not only for profile pages.

**Comment by gaurav-handysolver** [comment]
> I found another problem! In Spaces the post section is also removed, not only for profile pages.

Okay, then what should we do? we can only override view files in themes folder not controller so, we don't pass any other information from controller to differentiate user profile and space.

**Comment by gaurav-handysolver** [comment]
> > I found another problem! In Spaces the post section is also removed, not only for profile pages.
> 
> Okay, then what should we do? we can only override view files in themes folder not controller so, we don't pass any other information from controller to differentiate user profile and space.

We will think what we can do to resolve this problem

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We put some PHP code to differentiate between user's profile and space controller. please check it

**Review by donni106 — APPROVED** [review]
Let's try that

**Comment by donni106** [comment]
Works better now! 🥇

**Pull request merged**
